### ISSUE TITLE
[FEATURE] remove infer-owner

### ISSUE THREAD

**Issue by nlf** [npm/promise-spawn#6]
# What / Why

We would like this module to be a Promise-y wrapper around `child_process.spawn` and little else. The current features of buffering stdout/stderr streams and returning the final result (optionally as a string) make sense in this context, however the behavior of inferring a uid/gid to run a process as is outside of the scope of concerns of this module.

**Comment by Foorack** [comment]
As this magic uid/gid inferring was re-introduced, can this issue be re-opened?

**Comment by yuki-js** [comment]
seemed reverted in #12, but README is not reverted.
