### ISSUE TITLE
[BUG] Probably does not work with WSL2

### ISSUE THREAD

**Issue by igoradamenko** [npm/promise-spawn#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm repo pkg` fails.

### Expected Behavior

`npm repo pkg` should open a browser page with `pkg` repo.

### Steps To Reproduce

```
$ npm repo axios
npm ERR! Cannot read properties of undefined (reading 'stdin')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ai/.npm/_logs/2023-04-09T13_02_08_591Z-debug-0.log
```

### Environment

- npm: 9.5.0
- Node: 18.15.0
- OS: Ubuntu 20.04
- platform: WSL2

**Comment by cg2916** [comment]
Bumping as this means that `npm login` fails for this reason on Node 18 on WSL.
